{
  "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
  "database.hostname": "__POSTGRES_HOSTNAME__",
  "database.port": "__POSTGRES_PORT__",
  "database.user": "__POSTGRES_USER__",
  "database.password": "${env:POSTGRES_PASSWORD}",
  "database.dbname": "__DATABASE_NAME__",
  "topic.prefix": "__TOPIC_PREFIX__",
  "plugin.name": "pgoutput",
  "slot.name": "__SLOT_NAME__",
  "publication.name": "__PUBLICATION_NAME__",
  "publication.autocreate.mode": "filtered",
  "table.include.list": "public.audit_log",
  "snapshot.mode": "initial",
  "tombstones.on.delete": "false",
  "json.handling.mode": "json",
  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schemas.enable": "false",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter.schemas.enable": "false",
  "heartbeat.interval.ms": "__HEARTBEAT_INTERVAL_MS__",
  "topic.creation.default.replication.factor": "1",
  "topic.creation.default.partitions": "__TOPIC_PARTITIONS__"
}
